version: '3.7'

services:
  api:
    build:
      context: ./app-api
      dockerfile: Dockerfile
    volumes:
      - './app-api:/usr/src/app'
      - './http_ca.crt:/usr/share/certs/http_ca.crt:ro'
    ports:
      - 8000:8000
    environment:
      - CLOUD_ID=<cloud_id>
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=o6G_pvRL=8P*7on+o6XH
      - ELASTICSEARCH_URL=https://192.168.0.3:9200

  client:
    build:
      context: ./app-ui
      dockerfile: Dockerfile
    volumes:
      - './app-ui:/usr/src/app'
    ports:
      - 3000:3000
    environment:
      - NEXT_API_URL=http://host.docker.internal:8000
    depends_on:
      - api
